### ISSUE TITLE
edge opens multiple udp ports

### ISSUE THREAD

**Issue by small-5** [n42n/n3n#56]
When the network is unavailable (for example, pppoe is not connected when the device is first started), the edge uses the specified udp port and randomly opens a port.
If the network is connected before edge start, only the specified port will be opened. Can we change it to only use the specified port at all times?
![image](https://github.com/user-attachments/assets/fcefd115-83d9-4412-8538-8da9163a0c03)
![image](https://github.com/user-attachments/assets/c67916cf-d316-4931-920e-ad638b99aa5a)
Are there any plans to support the use of ipv6 between edges?
Thanks!

**Comment by hamishcoleman** [comment]
That is quite strange - I'm not aware of any intentional code to open two UDP ports.  Are you able to run the edge with verbose logging and attach the log file?

There are definitely plans to support the use of IPv6 - I have been working on refactoring code to allow that to happen recently

**Comment by hamishcoleman** [comment]
Thanks for your log.  Especially happy that you included all the env vars and command line args for me to quickly reproduce.

There is a filehandle leak in the detect_local_ip_address() function in the error case (in your case, caused by no network available).  This socket is never used again and only created once, so it is a benign bug that just causes an extra socket to show up.

I will create a bugfix release in the next couple of days and update this ticket.

**Comment by small-5** [comment]
Thanks, I will test https://github.com/n42n/n3n/pull/57 later and tell you the results.

**Comment by small-5** [comment]
https://github.com/n42n/n3n/pull/57 Fixed this problem, no additional ports are opened anymore.Thanks!
